name: 🌐 JavaScript Debug Builds
on:
  workflow_call:

# Global Settings
env:
  # Only used for the cache key. Increment version to force clean build.
  GODOT_BASE_BRANCH: 3.x
  SCONSFLAGS: verbose=yes warnings=all werror=yes
  EM_VERSION: 3.1.45
  EM_CACHE_FOLDER: "emsdk-cache"

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-javascript
  cancel-in-progress: true

jobs:
  javascript-debug-template:
    runs-on: "ubuntu-22.04"
    name: Template (target=release_debug, tools=no)

    steps:
      - uses: actions/checkout@v4

      - name: Set up Emscripten latest
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: Verify Emscripten setup
        run: |
          emcc -v

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} optimize=size disable_3d=yes module_bmp_enabled=no module_bullet_enabled=no module_camera_enabled=no module_csg_enabled=no module_cvtt_enabled=no module_dds_enabled=no module_denoise_enabled=no module_enet_enabled=no module_etc_enabled=yes module_fbx_enabled=no module_freetype_enabled=yes module_gdnative_enabled=no module_gdscript_enabled=yes module_gridmap_enabled=no module_hdr_enabled=no module_jpg_enabled=no module_jsonrpc_enabled=yes module_lightmapper_cpu_enabled=no module_mbedtls_enabled=yes module_minimp3_enabled=no module_mobile_vr_enabled=no module_mono_enabled=no module_ogg_enabled=yes module_opensimplex_enabled=yes module_opus_enabled=yes module_pvr_enabled=no module_raycast_enabled=no module_recast_enabled=no module_regex_enabled=yes module_squish_enabled=no module_stb_vorbis_enabled=yes module_svg_enabled=yes module_tga_enabled=no module_theora_enabled=no module_tinyexr_enabled=no module_upnp_enabled=no module_vhacd_enabled=no module_visual_script_enabled=no module_vorbis_enabled=yes module_webm_enabled=no module_webp_enabled=no module_webrtc_enabled=no module_websocket_enabled=no module_webxr_enabled=no module_xatlas_unwrap_enabled=no 
          platform: javascript
          target: release_debug
          tools: false
          cache-name: javascript-debug-template

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
